run-name: Testing

on:
  workflow_dispatch:

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.30.0
      
      - name: Testing connection
        run: |
          cd scripts/
          python test.py
          cd ../

